### PR TITLE
This testcase fails when it should not

### PR DESCRIPTION
**Pull request by Zae**
DO NOT MERGE

This is adds a testcase that fails when I think it should not.

Related to #3

### CODE REVIEW

**Comment by nunomaduro** [comment]
Can you try to debug this to track this specific line of this problem ? Maybe try to find a fix?

**Comment by brunogaspar** [comment]
Without digging much into the source of either packages, this seems a "limitation" of the native DOMDocument.

Since your example does not have a root element, it fails. This can probably be reproduced with any other fixture by removing their root elements perhaps.

Don't have any good suggestions to fix this, but you can fix your test by having a root element or somehow the package itself apply a root element 🤷‍♂

**Comment by SimoTod** [comment]
Yeah, as @brunogaspar pointed out, the crawler "fixes" that html transforming the first and third line to paragraphs. At this point, `$crawler` contains a list of 3 DOM nodes. `outerHtml` only returns the html of the first node as per documentation.
It should probably loop on all the DOM nodes or something like that.
I'm about to go to sleep now but I can have a look tomorrow and send a PR if nobody fixes it first.

**Comment by fdalcin** [comment]
> Yeah, as @brunogaspar pointed out, the crawler "fixes" that html transforming the first and third line to paragraphs. At this point, `$crawler` contains a list of 3 DOM nodes. `outerHtml` only returns the html of the first node as per documentation.
> It should probably loop on all the DOM nodes or something like that.
> I'm about to go to sleep now but I can have a look tomorrow and send a PR if nobody fixes it first.

At the moment the crawler "fixes"the html the output would be something like this:

```html
<body>
    <p>WIDGETBEFBEFOREArchivesAFTER</p>
    <ul></ul>
    WIDGETAFT
</body>
```
As @brunogaspar said, wrapping the content with a ```div``` tag for example would work as expected for now. 

I believe that the issue lies on this line:
https://github.com/nunomaduro/laravel-mojito/blob/5185a54d65caf79623cc33317e511970a5178fbc/src/ViewAssertion.php#L32

**Comment by nunomaduro** [comment]
Maybe we can configure the crawler to not fixed and throw an error ?

**Comment by SimoTod** [comment]
@fdalcin Nah, it actually inserts both `html` and `body` when missing so the 2 calls to children() make sense.

It's definitely related to `outerHTML` returning only the content of the first node which would be a blocker for any views not having a single root node. 

That's an easy fix which would work for views like (note the correct tags) 
```html
<p>WIDGETBEFBEFOREArchivesAFTER</p>
<ul></ul>
<p>WIDGETAFT</p>
```

As you said though, the parser "fixes" the first line but not the last line (not sure why) and `Crawler::children()` returns only element nodes and it ignores text nodes so the "fixed" html is
```html
<p>WIDGETBEFBEFOREArchivesAFTER</p>
<ul></ul>
```
This looks more like a synfony bug (if it's even a bug, i think html should be valid, really) 

@nunomaduro it could be an option but I haven't looked into it yet so I don't know how feasible it is. Are you okay with me looking into it today or do you want to fix it by yourself? Thanks

**Comment by fdalcin** [comment]
@SimoTod sorry, I missed the ```html``` tag in there. Not saying that those 2 children() calls don't make sense, though.

I agree that html should be valid and throwing an error would be appropriate.

**Comment by nunomaduro** [comment]
Fixed by https://github.com/nunomaduro/laravel-mojito/pull/8

**Pull request closed without merging**
