### PR TITLE
Bug -  in() method improvements

### LINKED ISSUE #10: `in()` method result may be incomplete
It may not be an issue but just my misunderstanding.

I was expecting the `in()` method to select all the DOM elements matching the given condition so we can assert against that subset but it seems to consider only the first match so there are no real differences between `first()` and `in()`

If we consider the welcome view in the test folder (https://github.com/nunomaduro/laravel-mojito/blob/master/tests/fixtures/welcome.html),  I would expect 
`$this->assertView('welcome')->in('.links a')->contains('Docs');` pass
`$this->assertView('welcome')->first('.links a')->contains('Docs');` pass
`$this->assertView('welcome')->in('.links a')->contains('Laracasts');` pass
`$this->assertView('welcome')->first('.links a')->contains('Laracasts');` fail
but right now we get
`$this->assertView('welcome')->in('.links a')->contains('Docs');` pass
`$this->assertView('welcome')->first('.links a')->contains('Docs');` pass
`$this->assertView('welcome')->in('.links a')->contains('Laracasts');` **fail???**
`$this->assertView('welcome')->first('.links a')->contains('Laracasts');` fail

I just wanted to get people's opinion since it could be just me misinterpreting the feature but, if we feel that `in()` should act as I described, I'm happy to PR that in.

### PR DESCRIPTION
**Pull request by SimoTod**
Fixes #10

### CODE REVIEW

**Comment by nunomaduro** [comment]
Don't forget that I still need to validate things that go the master branch.

**Comment by SimoTod** [comment]
Ah sorry, I thought you checked the previous post. I'm away from my laptop now. I'll revert the change and restore the Pr later tonight. 👍

**Comment by nunomaduro** [comment]
You don't have to revert, sounds good here.

**Comment by SimoTod** [comment]
Cool, I'll be more careful next time. Thanks for the heads up.

**Pull request merged**
