### PR TITLE
Bug - Views with multiple root nodes

### LINKED ISSUE #3: assertions are wrong because of wrong html output
Hi,

It seems that DomCrawler changes my HTML which makes my tests fail.

Lets say the output from my view is:
~~~
WIDGETBEFBEFOREArchivesAFTER
<ul></ul>
WIDGETAFT
~~~

And I test like this:

~~~
static::assertView('view)
            ->contains('BEFORE')
            ->contains('AFTER')
            ->contains('WIDGETBEF');
            ->contains('WIDGETAFT');
~~~

This fails because mojito thinks the output of the view is:

~~~
<p>WIDGETBEFBEFOREArchivesAFTER</p>
~~~

This is definitely not the output of the view, but this is probably what DomCrawler makes of it when it imports the HTML.

### PR DESCRIPTION
**Pull request by SimoTod**
Closes #3 

Big thanks to @Zae for providing the fixture and test.

Quite simple solution but it will stop the crawler from removing/fixing standalone text nodes (outside html tags) since we already know the original html, it's easier to use it rather than crawl it and rebuild it. 
It will also add support for partial views with valid HTML but multiple root nodes: The previous implementation was using outerHTML which only consider the first DOM node (see https://symfony.com/doc/current/components/dom_crawler.html#component-dom-crawler-dumping).

### CODE REVIEW

**Comment by nunomaduro** [comment]
Thanks!

**Comment by nunomaduro** [comment]
If you are interested @SimoTod, I can add you as maintainer of this package. let me know.

**Comment by SimoTod** [comment]
@nunomaduro it sounds good. I'm happy to help with any future issues. 👍

**Comment by nunomaduro** [comment]
Done https://github.com/nunomaduro/laravel-mojito/invitations

**Pull request merged**
