### PR TITLE
feat: add empty assertions

### PR DESCRIPTION
**Pull request by chaseconey**
## Overview

This PR adds a couple of additional assertions:

- `empty()`
- ~~`notEmpty()`~~

## Usage

You can use these new assertions just as you would the other chainable functions. For example, to see if a view selector has no content, you can do something like this:

```php
$this->assertView('empty')->in('.empty-div')->empty();
```

### CODE REVIEW

**Comment by SimoTod** [comment]
Thanks @chaseconey. The assertion can be useful. I've got a few questions about `empty()`. 

In the error message you mention text but the check is actually testing the html content. For instance
```html
<div>
<div class="empty-div">
<p></p>
</div>
</div>
```
 would fail the check but there's no visual content in the view. Is that expected?

Html is weird with spaces and newlines, something like 
```html
<div>
<div class="empty-div"> 
</div>
</div>
```
Would fail the test although one could argue that `empty-div` is empty. Is that expected?

`In()` returns a list of nodes (opposite to `first()`) but `crawler->html()` only returns the first node so something like
```html
<div>
<div class="empty-div"></div>
<div class="empty-div">ops</div>
</div>
```
 would pass the check, despite the second note having contents. I'm not sure this is the right behaviour here. 

Could you also update the readme to describe what the assertion would do? 

----

About `notEmpty()`, I think @nunomaduro in the past said he would rather have a `not()` function that you would chain to any assertion. I.e. `not()->empty()`, `not()->contains()`, etc
Maybe it's worth focusing on empty for now unless someone has a concrete use case.

Thanks again for sending the PR.

**Comment by chaseconey** [comment]
> In the error message you mention text but the check is actually testing the html content. For instance
> 
> ```
> <div>
> <div class="empty-div">
> <p></p>
> </div>
> </div>
> ```
> 
> would fail the check but there's no visual content in the view. Is that expected?

I guess this is up for debate. I can see reasons to go both ways. Do you have a preference?


> 
> Html is weird with spaces and newlines, something like
> 
> ```
> <div>
> <div class="empty-div"> 
> </div>
> </div>
> ```
> 
> Would fail the test although one could argue that `empty-div` is empty. Is that expected?

Good call here, I can update the tests and implementation on this one.


> `In()` returns a list of nodes (opposite to `first()`) but `crawler->html()` only returns the first node so something like
> 
> ```
> <div>
> <div class="empty-div"></div>
> <div class="empty-div">ops</div>
> </div>
> ```
> 
> would pass the check, despite the second note having contents. I'm not sure this is the right behaviour here.

Let me mess with this one and see if there is a more accurate way to assert on the full content (also depending on the above answer).


> Could you also update the readme to describe what the assertion would do?

Definitely!

> 
> About `notEmpty()`, I think @nunomaduro in the past said he would rather have a `not()` function that you would chain to any assertion. I.e. `not()->empty()`, `not()->contains()`, etc
> Maybe it's worth focusing on empty for now unless someone has a concrete use case.

So are you saying to remove the `notEmpty` in the meantime?

**Comment by SimoTod** [comment]
> I guess this is up for debate. I can see reasons to go both ways. Do you have a preference?

I don't have a strong opinion, we just need to make sure that the error message and the readme explain clearly what's expected. Currently it prints something like `... the text "<p></p>" is not empty ...` . 

> So are you saying to remove the `notEmpty` in the meantime?


Yes please, we can readd it later on if needed once we get a stable implementation of empty. Thanks

**Comment by chaseconey** [comment]
@SimoTod let me know if that covers your feedback!

**Review by SimoTod — APPROVED** [review]
Thanks 

@nunomaduro are we okay to release this one?

**Comment by nunomaduro** [comment]
@SimoTod Sure.

**Review by owenvoke — APPROVED** [review]

**Pull request merged**
